# Based on https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/ca.conf
[req]
distinguished_name = req_distinguished_name
prompt             = no
x509_extensions    = ca_x509_extensions

[ca_x509_extensions]
basicConstraints = CA:TRUE
keyUsage         = cRLSign, keyCertSign

[req_distinguished_name]
C   = DE
ST  = Musterland
L   = Musterhausen
CN  = CA
