# Kube Proxy Section
[req]
distinguished_name = req_distinguished_name
prompt             = no
req_extensions     = req_extensions

[req_extensions]
basicConstraints     = CA:FALSE
extendedKeyUsage     = clientAuth, serverAuth
keyUsage             = critical, digitalSignature, keyEncipherment
nsCertType           = client
nsComment            = "Kube Proxy Certificate"
subjectAltName       = DNS:kube-proxy, IP:127.0.0.1
subjectKeyIdentifier = hash

[req_distinguished_name]
CN = system:kube-proxy
O  = system:node-proxier
C  = DE
ST = Musterland
L  = Musterhausen
