# Controller Manager
[req]
distinguished_name = req_distinguished_name
prompt             = no
req_extensions     = req_extensions

[req_extensions]
basicConstraints     = CA:FALSE
extendedKeyUsage     = clientAuth, serverAuth
keyUsage             = critical, digitalSignature, keyEncipherment
nsCertType           = client
nsComment            = "Kube Controller Manager Certificate"
subjectAltName       = DNS:kube-controller-manager, IP:127.0.0.1
subjectKeyIdentifier = hash

[req_distinguished_name]
CN = system:kube-controller-manager
O  = system:kube-controller-manager
C  = DE
ST = Musterland
L  = Musterhausen
